llm:
  # api_type: "openai"
  # model: 'gpt-3.5-turbo'
  api_type: "open_llm"
  model: 'TA/meta-llama/Llama-3-8b-chat-hf'
  # model: 'TA/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo'
  base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  api_key: "sk-SL2TWFYq97803d15F1D5T3BlbKFJ9dCf90F93b374a52839a"

embedding:
  api_type: "hf"  # or  ollama / etc.
  api_key: "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"
  # base_url: "https://cfcus02.opapi.win/v1"  # or forward url / other llm url
  # api_key: "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"
  model: "BAAI/bge-m3"


  cache_dir: "/ssddata/zhengjun/GraphRAG-master/cache"
  
  dimensions: 1024 # 更换模型时记得更改维度
  max_token_size: 8102
  embed_batch_size: 128
  embedding_func_max_async: 16
 
data_root: /ssddata/zhengjun/GraphRAG-master/Data # Root directory for data

# working_dir: ./test_book # Result directory for the experiment
# exp_name: test_tog # Experiment name

working_dir: /ssddata/zhengjun/Dataset_tests # Result directory for the experiment
exp_name: tree_graph # Experiment name
